spring.datasource.url=jdbc:mysql://localhost:3306/backend_nls
spring.datasource.username=backend
spring.datasource.password=backend
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
omdb.api.key=28f879ef
tmdb.api.key=831f44d8cc9cd036755ce59cfd33c62c
omdb.api.url=https://www.omdbapi.com/
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
